#!/bin/sh

#-------------------------------------------------------------------------------
# Name:        jones_clear_folders.sh
# Purpose:     Delete contents of downstream folders before running all code
#	       Copy images into paper/figures that are not generated by
#	       code but are part of paper
#
# Created:     8 November, 2023
#-------------------------------------------------------------------------------

# Script relies on $REPODIR and $DBDIR variables exported from jones_bash_file.sh

# DELETE ALL INTERMEDIATE DATA FILES IN DROPBOX
find "$DBDIR/intdata" -type f -delete

# DELETE ALL FIGURES, TABLES, AND SINGLE NUM TEX FILES STORED IN REPO RESULTS
find "$REPODIR/output/figures" -type f -delete
find "$REPODIR/output/tables" -type f -delete
find "$REPODIR/output/tex_numbers" -type f -delete

# DELETE COMPILED PAPER
rm "$REPODIR/paper/KS_JonesAct.pdf"
rm "$REPODIR/paper/KS_JonesAct_appx.pdf"

# COPY IMAGES FROM DROPBOX TO REPO
cp "$DBDIR/images/EIA_PADDmap_notitle.pdf" "$REPODIR/output/figures"
cp "$DBDIR/images/MapFlowsFigure.pdf" "$REPODIR/output/figures"

# Clean up log files
rm *.log

exit
